CREATE TABLE channels (id BIGINT AUTO_INCREMENT NOT NULL, description VARCHAR(255), name VARCHAR(30), PRIMARY KEY (id))
CREATE TABLE videos (id BIGINT AUTO_INCREMENT NOT NULL, description VARCHAR(255), file VARCHAR(100) NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))
CREATE TABLE videoLists (id BIGINT AUTO_INCREMENT NOT NULL, position INTEGER, video BIGINT, PRIMARY KEY (id))
CREATE TABLE schedules (id BIGINT AUTO_INCREMENT NOT NULL, period INTEGER, channel BIGINT, PRIMARY KEY (id))
CREATE TABLE machines (id BIGINT AUTO_INCREMENT NOT NULL, hash VARCHAR(255) UNIQUE, last_updated DATETIME, name VARCHAR(255) UNIQUE, status VARCHAR(255), channel BIGINT, PRIMARY KEY (id))
CREATE TABLE users (ID BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(255), password VARCHAR(255), username VARCHAR(255) UNIQUE, PRIMARY KEY (ID))
CREATE TABLE commands (id BIGINT AUTO_INCREMENT NOT NULL, argument VARCHAR(255), command VARCHAR(255) NOT NULL, executed DATETIME NOT NULL, requested DATETIME NOT NULL, status VARCHAR(255), machine BIGINT, PRIMARY KEY (id))
CREATE TABLE schedules_videoLists (Schedule_id BIGINT NOT NULL, videoList_id BIGINT NOT NULL, PRIMARY KEY (Schedule_id, videoList_id))
ALTER TABLE videoLists ADD CONSTRAINT FK_videoLists_video FOREIGN KEY (video) REFERENCES videos (id)
ALTER TABLE schedules ADD CONSTRAINT FK_schedules_channel FOREIGN KEY (channel) REFERENCES channels (id)
ALTER TABLE machines ADD CONSTRAINT FK_machines_channel FOREIGN KEY (channel) REFERENCES channels (id)
ALTER TABLE commands ADD CONSTRAINT FK_commands_machine FOREIGN KEY (machine) REFERENCES machines (id)
ALTER TABLE schedules_videoLists ADD CONSTRAINT FK_schedules_videoLists_videoList_id FOREIGN KEY (videoList_id) REFERENCES videoLists (id)
ALTER TABLE schedules_videoLists ADD CONSTRAINT FK_schedules_videoLists_Schedule_id FOREIGN KEY (Schedule_id) REFERENCES schedules (id)
